classDiagram

    %% application
    class TicketBoxApplication
    TicketBoxApplication --> TicketOrderController : XXXTicketOrderRequest
    TicketBoxApplication --> PerformanceController : XXXPerformanceRequest

    %% controller
    class TicketOrderController
    TicketOrderController --> TicketOrderService : TicketParam

    class PerformanceController
    PerformanceController --> PerformanceService : PerformanceParam

    class TicketOrderService
    TicketOrderService --> TicketOrderRepository : TicketOrder
    TicketOrderService --> TicketRepository : Ticket

    class PerformanceService
    PerformanceService --> PerformanceRepository : Performance

    %% persistence
    class TicketRepository
    TicketRepository --> tickets : TicketEntity

    class TicketOrderRepository
    TicketOrderRepository --> ticket_orders : TicketOrderEntity

    class PerformanceRepository
    PerformanceRepository --> performances