flowchart TD
    start --> selectTicket[Select Ticket]
    selectTicket --> addTicket[Add Ticket]
    addTicket --> gatherTicketOrder[Gather tickets to ticket order]
    gatherTicketOrder --> order[Order Tickets]
    order --> terminate
