spring:
  datasource:
    url: ENC(vaaLMlh362VO9DtQZuNWkXxZR8xBbwRadgCpq/5iCcC5KSwHw5U6qa1+xT3+NYkX)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(RcbrrJ9GpfYVdV0pxfHQaQ==)
    password: ENC(qlVGWfXJE9xbopOJ2TbWhxvMGDr8MCj9)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    provider-name: SunJCE
    pool-size: 2
    key-obtention-iterations: 1000
    string-output-type: base64